function func_addJsonFields(fp_d)

  fprintf('\n%s\n%s - Adding specific json fields\n',...
    repmat('=',72,1),datestr(now,'yyyy-mm-dd hh:MM:ss'))
  
  clearvars cfg
  cfg.institute  = 'University Hospital Essen';
  cfg.department = 'Department of Neurology and Center for Translational Neuro- and Behavioral Sciences (C-TNBS)';
  cfg.address    = 'Hufelandstrasse 55, 45147 Essen, Germany';
  cfg.taskname   = 'fear';
  cfg.taskDescr  = 'Acquisition, extinction, and extinction recall of conditioned fear responses';

  instructions = {
    'ses-1_run-1'  ['Phase 1: Wir zeigen Ihnen verschiedene Symbole. '...
                    'In dieser Phase werden Sie keine elektrische '...
                    'Simulation erhalten. Bitte bleiben Sie ruhig '...
                    'sitzen und beobachten Sie aufmerksam die '...
                    'Praesentation auf dem Bildschirm. '...
                    '[phase 1: We will show you different symbols. '...
                    'In this phase you will not receive any electrical'...
                    'stimulation. Please remain calmly seated and watch'...
                    'carefully the presentation on the screen.]' ];
    'ses-1_run-2'  ['Phase 2: Jetzt beginnt die eigentliche Testphase. '...
                    'Bitte achten Sie auf moegliche Zusammenhaenge '...
                    'zwischen den gezeigten Symbolen und der '...
                    'elektrischen Stimulation. Bleiben Sie ruhig '... 
                    'sitzen und beobachten Sie aufmerksam die '...
                    'Praesentation auf dem Bildschirm. '...
                    '[Phase 2 : Now begins the actual test phase. '...
                    'Please pay attention to a potential connection '...
                    'between the symbols displayed and the electric '...
                    'stimulations. Please remain calmly seated and '...
                    'watch carefully the presentation on the screen.]' ];
    'ses-2_run-1'  ['Phase 3: Bitte bleiben Sie ruhig sitzen und '...
                    'beobachten Sie aufmerksam die Präsentation '...
                    'auf dem Bildschirm. [Phase 3 : Please remain '...
                    'calmly seated and watch carefully the '...
                    'presentation on the screen.]' ];
    'ses-3_run-1'  ['Phase 4: Bitte bleiben Sie ruhig sitzen und '...
                    'beobachten Sie aufmerksam die Präsentation '...
                    'auf dem Bildschirm. [Phase 4 : Please remain '...
                    'calmly seated and watch carefully the '...
                    'presentation on the screen.]'];
    'ses-3_run-2'  ['Phase 5: Bitte bleiben Sie ruhig sitzen und '...
                    'beobachten Sie aufmerksam die Präsentation '...
                    'auf dem Bildschirm. [Phase 5 : Please remain '...
                    'calmly seated and watch carefully the '...
                    'presentation on the screen.]'];
    };
  instructions(:,1) = cellfun(@(x) [x(1:5) '_task-'  cfg.taskname  ...
    x(6:end)] , instructions(:,1),'uni',0);
  fl = ter_listFiles(fp_d,['sub-*task-' cfg.taskname  '*.json']);

  for i=1:numel(fl)
    jinfo0 = jsondecode(fileread(fl{i}));
    jinfo = jinfo0;
    jinfo.TaskName = cfg.taskname;
    jinfo.TaskDescription = cfg.taskDescr;
    jinfo.InstitutionName  = cfg.institute;
    jinfo.InstitutionalDepartmentName = cfg.department;
    jinfo.InstitutionAddress = cfg.address;
    
    ind = cellfun(@(x) contains(fl{i},x),instructions(:,1) );
    jinfo.Instructions = instructions(ind,2) ;
    if not(isequal(jinfo0,jinfo))
      fprintf('Updating file %s\n', fl{i});
      ter_savePrettyJson(fl{i},jinfo)
    end
  end


  
  

